/*
 * squad64.c - raise the user squad cap from 32 to 32 + SQUAD_EXT_CAP (64 by default).
 *
 * Built by squad_caps.py into a flat Thumb blob at the end of CAVE3; its .bss lives in MODDATA.
 *
 * Design ("canonical 32 view + user overflow"): every stock structure keeps its layout and a valid
 * view of at most 32 players, so code that is not patched keeps working and simply sees the first 32
 * players of the user squad. The players beyond 32 live in side tables owned by this file:
 *
 *   g_lx  user team link overflow  (TTeamPlayerLink entries 32..63: spec + id)
 *   g_ux  season lineup overflow   (CTeamLineup slots 32..63 of the season team management)
 *   g_sx  season player states     (CSeasonPlayerState of the players in g_ux)
 *   g_pool TPlayerInfo for overflow players, for the front-end CTeam (squad screen)
 *
 * Invariant kept by resync_partition(): the stock 32-part of the user link, of the season lineup and of
 * the season player states hold exactly the players of lineup slots 0..31 (XI, bench, first reserves),
 * the overflow tables hold the players of lineup slots 32.. in lineup order. Only the user team (0x102)
 * and only the season CTeamManagement (MP_cMyProfile + 0x14 + 0x6e0) have overflow tables; AI teams and
 * every copy of the team management (match setup, in-game, network) stay at 32.
 *
 * Rules: no absolute addresses (everything PC-relative, -fPIC + hidden symbols), no initialised pointer
 * data, no libgcc calls (no division), no floating point except EnergyReplenish (VFP, softfp ABI).
 */
#include <stdint.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef int32_t s32;

#ifndef SQUAD_EXT_CAP
#define SQUAD_EXT_CAP 32
#endif
#define EXT_STORE 32                 /* storage and save format are always 32 overflow entries */
#define EXT_CAP (SQUAD_EXT_CAP > EXT_STORE ? EXT_STORE : SQUAD_EXT_CAP)
#define USER_TEAM 0x102
#define EMPTY_ID 0xFFDE
#ifndef SAVE_GATE
#define SAVE_GATE 0xB6               /* profile save version that carries the overflow blocks */
#endif
#define POOL_N 64
#define INFO_SIZE 0xB0

#define HIDDEN __attribute__((visibility("hidden")))
#define API __attribute__((visibility("hidden"), used, noinline))

typedef struct { s32 team, count; u32 spec[32]; s32 id[32]; } Link;          /* 0x108 */
typedef struct { u8 n; u8 pad; u16 id[32]; u8 adjust; } Lineup;              /* 0x43 used */
typedef struct { u16 id; u16 w2; u8 injury; u8 b5; u16 energy; u8 susp; u8 yellows; } State; /* 10 */

typedef struct { s32 count; u32 spec[EXT_STORE]; s32 id[EXT_STORE]; } LinkExt;
typedef struct { s32 count; u16 id[EXT_STORE]; } LuExt;

_Static_assert(sizeof(State) == 10, "CSeasonPlayerState is 10 bytes");
_Static_assert(__builtin_offsetof(Lineup, id) == 2, "lineup ids at +2");
_Static_assert(__builtin_offsetof(Lineup, adjust) == 0x42, "lineup adjust at +0x42");
_Static_assert(sizeof(Link) == 0x108, "TTeamPlayerLink is 0x108 bytes");

/* ---- game data (link-time addresses, accessed PC-relative) ---- */
extern u8 MP_cMyProfile[] HIDDEN;              /* 0x84a260 */
extern u8 *DB_ms_pInstance HIDDEN;             /* 0x75cca4: CDataBase* */
extern u8 MatchSetup_ms_tInfo[] HIDDEN;        /* 0x7c2aac */
extern u8 MC_bResettingProfile[] HIDDEN;       /* 0x83f251 */

/* ---- game functions (Thumb) ---- */
extern Link *GetTeamLink(int team) HIDDEN;
extern void UpdateStatsAddPlayer(void *season, int team, int pid, int b) HIDDEN;
extern void UpdateStatsRemovePlayer(void *season, int team, int pid, int b) HIDDEN;
extern void SerInt(void *ser, s32 *p, int minver) HIDDEN;
extern void SerU16(void *ser, u16 *p, int minver) HIDDEN;
extern void SerU8(void *ser, u8 *p, int minver) HIDDEN;
extern void SpecSerialize(u32 *spec, void *ser) HIDDEN;
extern void StateSerialize(State *st, void *ser) HIDDEN;
extern void TPlayerInfoCtor(void *info) HIDDEN;
extern int GetPlayerInfo(void *info, int id, int team, int b, void *rom, int x, void *link, int y) HIDDEN;
extern void FixLink(Link *l) HIDDEN;
extern void UpdateTeamRoles(void *cteam) HIDDEN;
extern void StateReduceInjury(State *st) HIDDEN;
extern void StateReduceSuspension(State *st) HIDDEN;
extern int CConfigGetVar(int var) HIDDEN;
extern int GetCreditRechargeSeconds(int x) HIDDEN;
extern int PU_GetGeneralPosFromPos(int pos) HIDDEN;
extern int CCore_InGame(void) HIDDEN;
extern int IsCreatedPlayerID(int id) HIDDEN;

/* ---- trampolines to the original bodies (generated by squad_caps.py) ---- */
extern void orig_AddPlayerToLink(void *db, int team, const u8 *info, const u8 *spec, int force, int dxi) HIDDEN;
extern void orig_RemovePlayerFromLink(void *db, int team, int pid, int upd) HIDDEN;
extern void orig_LinkSerialize(Link *l, u8 *ser) HIDDEN;
extern void orig_NewDreamTeam(void) HIDDEN;
extern void orig_LuRemovePlayerByID(Lineup *lu, int id) HIDDEN;
extern void orig_LuSerialize(Lineup *lu, u8 *ser) HIDDEN;
extern void orig_LuReset(Lineup *lu) HIDDEN;
extern void *orig_LuCtor(Lineup *lu) HIDDEN;
extern void orig_ForceFirst11(Lineup *lu, int id) HIDDEN;
extern void orig_TmAddPlayer(u8 *tm, int id) HIDDEN;
extern void orig_TmRemovePlayerByID(u8 *tm, int id) HIDDEN;
extern void orig_TmSerialize(u8 *tm, u8 *ser) HIDDEN;
extern void orig_TmReset(u8 *tm) HIDDEN;
extern void orig_TmNextSeason(u8 *tm) HIDDEN;
extern int orig_EnergyReplenish(u8 *tm, int full, int secs) HIDDEN;
extern void orig_ReduceInjSusp(u8 *tm) HIDDEN;
extern int orig_CanSwap(u8 *tm, int id1, int id2, int idx1, int idx2) HIDDEN;
extern void orig_TmVerify(u8 *tm) HIDDEN;
extern void orig_TmSetDefaults(u8 *tm, int team, int type, void *custom, void *players) HIDDEN;
extern void orig_PlayersLoad(void *db, u8 *cteam, u8 *tm, int x) HIDDEN;
extern u8 *orig_CTeamGetPlayerInfoByID(u8 *cteam, int id) HIDDEN;
extern void orig_CTeamSwapPlayers(u8 *cteam, int i, int j) HIDDEN;
extern int orig_LuHaveCreatedPlayerInSquad(Lineup *lu) HIDDEN;

/* ---- state ---- */
LinkExt g_lx HIDDEN;
LuExt g_ux HIDDEN;
State g_sx[EXT_STORE] HIDDEN;
u8 g_pool[POOL_N][INFO_SIZE] HIDDEN __attribute__((aligned(8)));
u16 g_pool_id[POOL_N] HIDDEN;
u32 g_pool_next HIDDEN;
u32 g_in_resync HIDDEN;
u32 g_stats[8] HIDDEN;                      /* debug counters: [0] resyncs [1] link moves [2] state moves */
static LinkExt s_lx_scratch;
static LuExt s_ux_scratch;
static State s_sx_scratch[EXT_STORE];

/* ---- freestanding helpers (gcc may emit calls to these) ---- */
HIDDEN void *memcpy(void *d, const void *s, u32 n) {
    u8 *dp = d; const u8 *sp = s;
    while (n--) *dp++ = *sp++;
    return d;
}
HIDDEN void *memmove(void *d, const void *s, u32 n) {
    u8 *dp = d; const u8 *sp = s;
    if (dp < sp) { while (n--) *dp++ = *sp++; }
    else { dp += n; sp += n; while (n--) *--dp = *--sp; }
    return d;
}
HIDDEN void *memset(void *d, int c, u32 n) {
    u8 *dp = d;
    while (n--) *dp++ = (u8)c;
    return d;
}

/* ---- addresses ---- */
static inline void *season(void) { return MP_cMyProfile + 0x14; }
static inline u8 *S_TM(void) { return MP_cMyProfile + 0x14 + 0x6e0; }
static inline Lineup *S_LU(void) { return (Lineup *)(MP_cMyProfile + 0x14 + 0x6e0 + 0x140); }
static inline State *tm_states(u8 *tm) { return (State *)tm; }
static inline u8 *tm_owner(u8 *tm) { return *(u8 **)(tm + 0x194); }
static inline u8 *ct_tm(u8 *ct) { return *(u8 **)(ct + 0x1014); }
static inline int lu_main(const Lineup *lu) { return lu->n > 32 ? 32 : lu->n; }

static int override_on(void) {
    u8 *d = DB_ms_pInstance;
    return d && *(u32 *)(d + 0x1c) != 0;
}
static int is_user_link(const Link *l) { return l && l->team == USER_TEAM && !override_on(); }

/* The user link in the live table (NULL while the database or live table is not set up). */
static Link *live_user_link(void) {
    u8 *d = DB_ms_pInstance;
    if (!d || *(u32 *)(d + 0x1c) || !*(u32 *)(d + 0x28) || *(s32 *)(d + 0x38) <= 0) return 0;
    return GetTeamLink(USER_TEAM);
}

static void state_clear(State *s) { memset(s, 0, sizeof *s); s->id = EMPTY_ID; }
static void state_setup(State *s, int id) {           /* CSeasonPlayerState::Setup */
    s->id = (u16)id; s->w2 = 0; s->injury = 0; s->energy = 0x927c; s->susp = 0; s->yellows = 0;
}

static void ext_clear_all(void) {
    memset(&g_lx, 0, sizeof g_lx);
    for (int i = 0; i < EXT_STORE; ++i) g_lx.id[i] = -1;
    g_ux.count = 0;
    for (int i = 0; i < EXT_STORE; ++i) g_ux.id[i] = EMPTY_ID;
    for (int i = 0; i < EXT_STORE; ++i) state_clear(&g_sx[i]);
    for (int i = 0; i < POOL_N; ++i) g_pool_id[i] = EMPTY_ID;
}
/* MODDATA starts zero-filled, but id 0 is not "empty" for these tables: initialise once, lazily. */
#define INIT_MAGIC 0x53513634u              /* "SQ64" */
u32 g_magic HIDDEN;
static void ensure_init(void) {
    if (g_magic != INIT_MAGIC) { ext_clear_all(); g_magic = INIT_MAGIC; }
}

static void ux_clear(LuExt *x) { x->count = 0; for (int i = 0; i < EXT_STORE; ++i) x->id[i] = EMPTY_ID; }
static void lx_clear(LinkExt *x) {
    x->count = 0;
    for (int i = 0; i < EXT_STORE; ++i) { x->spec[i] = 0; x->id[i] = -1; }
}

/* ---- overflow lookups ---- */
static int lx_find(int pid) {
    for (int i = 0; i < g_lx.count; ++i) if (g_lx.id[i] == pid) return i;
    return -1;
}
static void lx_remove(int k) {
    for (int i = k; i + 1 < g_lx.count; ++i) { g_lx.id[i] = g_lx.id[i + 1]; g_lx.spec[i] = g_lx.spec[i + 1]; }
    g_lx.count--;
    g_lx.id[g_lx.count] = -1; g_lx.spec[g_lx.count] = 0;
}
static int ux_find(int id) {
    for (int i = 0; i < g_ux.count; ++i) if (g_ux.id[i] == (u16)id) return i;
    return -1;
}
static void ux_remove(int k) {
    for (int i = k; i + 1 < g_ux.count; ++i) g_ux.id[i] = g_ux.id[i + 1];
    g_ux.count--;
    g_ux.id[g_ux.count] = EMPTY_ID;
}
static State *sx_find(int id) {
    for (int i = 0; i < EXT_STORE; ++i) if (g_sx[i].id != EMPTY_ID && g_sx[i].id == (u16)id) return &g_sx[i];
    return 0;
}
static State *sx_free(void) {
    for (int i = 0; i < EXT_STORE; ++i) if (g_sx[i].id == EMPTY_ID) return &g_sx[i];
    return 0;
}
/* season lineup slot of a player: 0..31 main, 32.. overflow, -1 absent */
static int lu_slot(int id) {
    Lineup *lu = S_LU();
    int n = lu_main(lu);
    for (int i = 0; i < n; ++i) if (lu->id[i] == (u16)id) return i;
    int k = ux_find(id);
    return k >= 0 ? 32 + k : -1;
}

/* ================= resync ================= */
typedef struct { u32 spec; s32 id; s32 slot; s32 was_main; } Entry;

static void part_link(void) {
    Link *L = live_user_link();
    if (!L) return;
    int m = L->count;
    if (m < 0) m = 0;
    if (m > 32) m = 32;
    Entry all[32 + EXT_STORE];
    int na = 0;
    for (int i = 0; i < m; ++i) { all[na].spec = L->spec[i]; all[na].id = L->id[i]; all[na].was_main = 1; na++; }
    for (int j = 0; j < g_lx.count && na < 32 + EXT_STORE; ++j) {
        all[na].spec = g_lx.spec[j]; all[na].id = g_lx.id[j]; all[na].was_main = 0; na++;
    }
    int want_main = 0;
    for (int i = 0; i < na; ++i) {
        all[i].slot = lu_slot(all[i].id);
        if ((all[i].slot >= 0 && all[i].slot < 32) || (all[i].slot < 0 && all[i].was_main)) want_main++;
    }
    /* more than 32 would-be main entries: demote main entries that are not in the lineup */
    int demote = want_main - 32;
    u8 in_main[32 + EXT_STORE];
    for (int i = 0; i < na; ++i) {
        int wm = (all[i].slot >= 0 && all[i].slot < 32) || (all[i].slot < 0 && all[i].was_main);
        in_main[i] = (u8)wm;
    }
    for (int i = na - 1; i >= 0 && demote > 0; --i)
        if (in_main[i] && all[i].slot < 0) { in_main[i] = 0; demote--; }
    /* new main: keep staying main entries in place, fill vacated positions with incoming ones */
    u32 nspec[32]; s32 nid[32];
    int nm = 0, changed = 0;
    int inc[32 + EXT_STORE], ninc = 0, pinc = 0;
    for (int i = m; i < na; ++i) if (in_main[i]) inc[ninc++] = i;
    for (int i = 0; i < m; ++i) {
        if (in_main[i]) { nspec[nm] = all[i].spec; nid[nm] = all[i].id; nm++; }
        else if (pinc < ninc) { int s = inc[pinc++]; nspec[nm] = all[s].spec; nid[nm] = all[s].id; nm++; changed = 1; }
        else changed = 1;                           /* vacated with nothing to fill: compact */
    }
    while (pinc < ninc && nm < 32) { int s = inc[pinc++]; nspec[nm] = all[s].spec; nid[nm] = all[s].id; nm++; changed = 1; }
    /* incoming entries that did not fit stay in the overflow */
    u8 placed[32 + EXT_STORE];
    for (int i = 0; i < na; ++i) placed[i] = 0;
    for (int i = 0; i < pinc; ++i) placed[inc[i]] = 1;
    for (int i = 0; i < m; ++i) if (in_main[i]) placed[i] = 1;
    /* new overflow: every entry not placed in main, ordered by lineup slot (absent players last) */
    LinkExt nx;
    lx_clear(&nx);
    for (int pass = 0; pass < 2; ++pass) {
        if (pass == 0) {
            for (int s = 32; s < 32 + EXT_STORE; ++s)
                for (int i = 0; i < na; ++i)
                    if (!placed[i] && all[i].slot == s && nx.count < EXT_STORE) {
                        nx.spec[nx.count] = all[i].spec; nx.id[nx.count] = all[i].id; nx.count++; placed[i] = 1;
                    }
        } else {
            for (int i = 0; i < na; ++i)
                if (!placed[i] && nx.count < EXT_STORE) {
                    nx.spec[nx.count] = all[i].spec; nx.id[nx.count] = all[i].id; nx.count++; placed[i] = 1;
                }
        }
    }
    if (nx.count != g_lx.count) changed = 1;
    for (int i = 0; i < nx.count && !changed; ++i) if (nx.id[i] != g_lx.id[i]) changed = 1;
    if (nm != m) changed = 1;
    if (!changed) return;
    for (int i = 0; i < nm; ++i) { L->spec[i] = nspec[i]; L->id[i] = nid[i]; }
    for (int i = nm; i < 32; ++i) { L->spec[i] = 0; L->id[i] = -1; }
    L->count = nm;
    g_lx = nx;
    g_stats[1]++;
    FixLink(L);                                     /* exactly 11 starters / one holder per role in the 32-part */
}

/* full = 1 only from the Verify-driven resync: it also drops states of players that left the lineup
 * (the stock Verify does the same for the 32-part) and creates missing states. The partial resync that
 * follows link/lineup edits only moves states across the 32 boundary, because the lineup can lag behind
 * the link for a moment (SignPlayer adds to the link before CTeamManagement::AddPlayer). */
static void part_states(int full) {
    State *ms = tm_states(S_TM());
    /* duplicates always; stale states (player not in the season lineup) only in full mode */
    for (int i = 0; i < 32; ++i) {
        if (ms[i].id == EMPTY_ID) continue;
        int dup = 0;
        for (int k = 0; k < i; ++k) if (ms[k].id == ms[i].id) dup = 1;
        if (dup || (full && lu_slot(ms[i].id) < 0)) state_clear(&ms[i]);
    }
    for (int j = 0; j < EXT_STORE; ++j) {
        if (g_sx[j].id == EMPTY_ID) continue;
        int dup = 0;
        for (int k = 0; k < 32; ++k) if (ms[k].id == g_sx[j].id) dup = 1;
        for (int k = 0; k < j; ++k) if (g_sx[k].id == g_sx[j].id) dup = 1;
        if (dup || (full && lu_slot(g_sx[j].id) < 0)) state_clear(&g_sx[j]);
    }
    /* swap outgoing main states with incoming overflow states in place */
    for (int i = 0; i < 32; ++i) {
        if (ms[i].id == EMPTY_ID || lu_slot(ms[i].id) < 32) continue;      /* stays main */
        for (int j = 0; j < EXT_STORE; ++j) {
            if (g_sx[j].id == EMPTY_ID) continue;
            int s = lu_slot(g_sx[j].id);
            if (s >= 0 && s < 32) {
                State t = ms[i]; ms[i] = g_sx[j]; g_sx[j] = t; g_stats[2]++;
                break;
            }
        }
    }
    /* remaining incoming -> free main slots, remaining outgoing -> free overflow slots */
    for (int j = 0; j < EXT_STORE; ++j) {
        if (g_sx[j].id == EMPTY_ID) continue;
        int s = lu_slot(g_sx[j].id);
        if (s >= 0 && s < 32)
            for (int i = 0; i < 32; ++i)
                if (ms[i].id == EMPTY_ID) { ms[i] = g_sx[j]; state_clear(&g_sx[j]); g_stats[2]++; break; }
    }
    for (int i = 0; i < 32; ++i) {
        if (ms[i].id == EMPTY_ID || lu_slot(ms[i].id) < 32) continue;
        State *f = sx_free();
        if (f) { *f = ms[i]; state_clear(&ms[i]); g_stats[2]++; }
    }
    if (!full) return;
    /* every lineup player needs a state */
    Lineup *lu = S_LU();
    int n = lu_main(lu);
    for (int s = 0; s < n + g_ux.count; ++s) {
        int id = s < n ? lu->id[s] : g_ux.id[s - n];
        if (id == EMPTY_ID) continue;
        int found = 0;
        for (int i = 0; i < 32 && !found; ++i) if (ms[i].id == (u16)id) found = 1;
        if (!found && sx_find(id)) found = 1;
        if (found) continue;
        State *f = 0;
        if (s < n) { for (int i = 0; i < 32; ++i) if (ms[i].id == EMPTY_ID) { f = &ms[i]; break; } }
        if (!f) f = sx_free();
        if (!f && s >= n) { for (int i = 0; i < 32; ++i) if (ms[i].id == EMPTY_ID) { f = &ms[i]; break; } }
        if (f) state_setup(f, id);
    }
}

/* Lineup 32-part full before the overflow is used (slots stay contiguous). */
static void lineup_fill(void) {
    Lineup *lu = S_LU();
    while (lu->n < 32 && g_ux.count > 0) {
        lu->id[lu->n] = g_ux.id[0];
        lu->n++;
        ux_remove(0);
    }
}

static void resync_mode(int full) {
    if (!live_user_link()) return;
    g_stats[0]++;
    lineup_fill();
    part_link();
    part_states(full);
}
static void resync_partition(void) { resync_mode(0); }

/* Only from the CTeamManagement::Verify wrapper (the stock consistency point). */
static void resync_full(void) {
    if (g_in_resync) return;
    Link *L = live_user_link();
    if (!L) return;
    g_in_resync = 1;
    Lineup *lu = S_LU();
    int n = lu_main(lu);
    /* overflow duplicates (of the 32-part or within itself) and players that left the link */
    for (int k = 0; k < g_ux.count;) {
        int id = g_ux.id[k], drop = 0;
        for (int i = 0; i < n; ++i) if (lu->id[i] == id) drop = 1;
        for (int j = 0; j < k; ++j) if (g_ux.id[j] == id) drop = 1;
        int in_link = lx_find(id) >= 0;
        for (int i = 0; i < L->count && i < 32; ++i) if (L->id[i] == id) in_link = 1;
        if (!in_link) drop = 1;
        if (drop) ux_remove(k); else ++k;
    }
    /* link players that are not in the lineup (e.g. a created player that went to the link overflow) */
    int total = L->count + g_lx.count;
    for (int t = 0; t < total; ++t) {
        int pid = t < L->count ? L->id[t] : g_lx.id[t - L->count];
        if (pid < 0 || lu_slot(pid) >= 0) continue;
        if (lu->n < 32) {
            lu->id[lu->n++] = (u16)pid;
            u8 *owner = tm_owner(S_TM());
            if (owner) owner[0x148]++;                /* CTeamManagement::AddPlayer does the same */
        } else if (g_ux.count < EXT_CAP) {
            g_ux.id[g_ux.count++] = (u16)pid;
        }
    }
    resync_mode(1);
    g_in_resync = 0;
}

/* ================= link ================= */
API u32 *sq_GetTeamSpecificData(int team, int pid) {
    ensure_init();
    if (team == -1) return 0;
    Link *L = GetTeamLink(team);
    if (!L) return 0;
    for (int i = 0; i < L->count && i < 32; ++i) if (L->id[i] == pid) return &L->spec[i];
    if (is_user_link(L)) { int k = lx_find(pid); if (k >= 0) return &g_lx.spec[k]; }
    return 0;
}

API int sq_ContainsPlayer(const Link *l, int pid) {
    ensure_init();
    for (int i = 0; i < l->count && i < 32; ++i) if (l->id[i] == pid) return 1;
    return is_user_link(l) && lx_find(pid) >= 0;
}

static u32 *link_entry(Link *l, int pid) {
    for (int i = 0; i < l->count && i < 32; ++i) if (l->id[i] == pid) return &l->spec[i];
    if (is_user_link(l)) { int k = lx_find(pid); if (k >= 0) return &g_lx.spec[k]; }
    return 0;
}
API int sq_GetPlayerShirtNum(Link *l, int pid) {
    ensure_init();
    u32 *e = link_entry(l, pid);
    return e ? *(u8 *)e : -1;
}
API void sq_SetPlayerShirtNum(Link *l, int pid, int num) {
    ensure_init();
    u32 *e = link_entry(l, pid);
    if (e) *(u8 *)e = (u8)num;
}
API void sq_SwapPlayerShirtNums(Link *l, int a, int b) {
    ensure_init();
    u32 *ea = link_entry(l, a), *eb = link_entry(l, b);
    if (!ea || !eb) return;
    u8 t = *(u8 *)ea; *(u8 *)ea = *(u8 *)eb; *(u8 *)eb = t;
}

API int sq_CanAddPlayer(int team, const u8 *info, int x) {
    ensure_init();
    (void)x;
    if (team == -1) return 2;
    Link *L = GetTeamLink(team);
    int user = is_user_link(L);
    int total = L->count + (user ? g_lx.count : 0);
    if (total >= (user ? 32 + EXT_CAP : 32)) return 0;
    return sq_ContainsPlayer(L, *(const u16 *)info) ? 1 : 2;
}

API int sq_CanAddCreatedPlayer(void) {
    ensure_init();
    Link *L = GetTeamLink(USER_TEAM);
    int total = L->count + (is_user_link(L) ? g_lx.count : 0);
    return total > 32 + EXT_CAP - 1 ? 0 : 2;
}

API int sq_GetFirstAvailableShirtNumber(int team, int is_gk, int pref) {
    ensure_init();
    Link *L = GetTeamLink(team);
    int user = is_user_link(L);
    int m = L->count;
    if (pref != -1) {
        int used = 0;
        for (int i = 0; i < m && i < 32; ++i) if ((u8)L->spec[i] == pref) used = 1;
        if (user) for (int k = 0; k < g_lx.count; ++k) if ((u8)g_lx.spec[k] == pref) used = 1;
        if (!used) return pref;
    }
    for (int n = 1; n <= 98; ++n) {
        if (n == 1 && !is_gk) continue;             /* number 1 is kept for goalkeepers */
        int used = 0;
        for (int i = 0; i < m && i < 32; ++i) if ((u8)L->spec[i] == n) used = 1;
        if (user) for (int k = 0; k < g_lx.count; ++k) if ((u8)g_lx.spec[k] == n) used = 1;
        if (!used) return n;
    }
    return -1;
}

API void sq_PU_GetPlayerPositionCounts(int team, int *gk, int *def, int *mid, int *fwd) {
    ensure_init();
    Link *L = GetTeamLink(team);
    int user = is_user_link(L);
    int total = L->count + (user ? g_lx.count : 0);
    for (int i = 0; i < total; ++i) {
        if (i >= L->count && !user) break;
        u32 spec = i < L->count ? L->spec[i] : g_lx.spec[i - L->count];
        int pos = PU_GetGeneralPosFromPos((int)(signed char)(spec >> 8));
        int *p = pos == 0 ? gk : pos == 1 ? def : pos == 2 ? mid : pos == 3 ? fwd : 0;
        if (p) (*p)++;
    }
}

API void sq_AddPlayerToLink(void *db, int team, const u8 *info, const u8 *spec, int force, int dxi) {
    ensure_init();
    Link *L = GetTeamLink(team);
    if (!is_user_link(L) || L->count < 32) {
        orig_AddPlayerToLink(db, team, info, spec, force, dxi);
        if (is_user_link(L)) resync_partition();
        return;
    }
    if (g_lx.count >= EXT_CAP) return;             /* full: silently ignored, like the stock 32 cap */
    int pid = *(const u16 *)info;
    if (sq_ContainsPlayer(L, pid)) return;
    int shirt = sq_GetFirstAvailableShirtNumber(L->team, info[0x80] == 0, spec[0]);
    int e = g_lx.count++;
    g_lx.id[e] = pid;
    g_lx.spec[e] = (u32)(u8)shirt | ((u32)spec[1] << 8);   /* role flags 0: overflow players hold no role */
    UpdateStatsAddPlayer(season(), team, pid, 0);
    resync_partition();
}

API void sq_RemovePlayerFromLink(void *db, int team, int pid, int upd) {
    ensure_init();
    Link *L = GetTeamLink(team);
    if (!is_user_link(L)) { orig_RemovePlayerFromLink(db, team, pid, upd); return; }
    int k = lx_find(pid);
    if (k >= 0) {
        lx_remove(k);
        if (upd) UpdateStatsRemovePlayer(season(), team, pid, 0);
    } else {
        orig_RemovePlayerFromLink(db, team, pid, upd);
    }
    resync_partition();
}

/* CalculateLinks user-player loop (detours at 0x209516 / 0x209728) */
API int sq_vlink_id(const Link *l, int i) {
    ensure_init();
    if (i < l->count) return l->id[i];
    if (is_user_link(l) && i - l->count < g_lx.count) return g_lx.id[i - l->count];
    return -1;
}
API int sq_vlink_count(const Link *l) { return l->count + (is_user_link(l) ? g_lx.count : 0); }

API void sq_LinkSerialize(Link *l, u8 *ser) {
    ensure_init();
    orig_LinkSerialize(l, ser);
    s32 ver = *(s32 *)(ser + 0x18);
    int saving = ser[0x1c] != 0;
    int live = l == live_user_link();
    LinkExt *x = live ? &g_lx : &s_lx_scratch;
    if (ver < SAVE_GATE) {
        if (!saving && live) lx_clear(&g_lx);
        return;
    }
    if (!live) lx_clear(&s_lx_scratch);
    SerInt(ser, &x->count, SAVE_GATE);
    for (int i = 0; i < EXT_STORE; ++i) SpecSerialize(&x->spec[i], ser);
    for (int i = 0; i < EXT_STORE; ++i) SerInt(ser, &x->id[i], SAVE_GATE);
    if (!saving) {
        if (x->count < 0 || x->count > EXT_CAP) x->count = x->count < 0 ? 0 : EXT_CAP;
        for (int i = x->count; i < EXT_STORE; ++i) { x->spec[i] = 0; x->id[i] = -1; }
    }
}

API void sq_NewDreamTeam(void) {
    ensure_init();
    ext_clear_all();
    orig_NewDreamTeam();
}

/* ================= lineup ================= */
static u16 *lu_ptr_idx(Lineup *lu, int i) {
    if ((u32)i < 32) return &lu->id[i];
    if (lu == S_LU() && i >= 32 && i - 32 < g_ux.count) return &g_ux.id[i - 32];
    return 0;
}
static u16 *lu_ptr_id(Lineup *lu, u16 id, int *idx) {
    for (int i = 0; i < 32; ++i) if (lu->id[i] == id) { *idx = i; return &lu->id[i]; }
    if (lu == S_LU()) { int k = ux_find(id); if (k >= 0) { *idx = 32 + k; return &g_ux.id[k]; } }
    *idx = -1;
    return 0;
}

API void sq_LuAddPlayer(Lineup *lu, int id) {
    ensure_init();
    int n = lu->n;
    if (n < 32) { lu->n = (u8)(n + 1); lu->id[n] = (u16)id; return; }
    if (lu == S_LU() && g_ux.count < EXT_CAP) g_ux.id[g_ux.count++] = (u16)id;
}

API int sq_LuGetID(Lineup *lu, int i) {
    ensure_init();
    if ((u32)i <= 31) return lu->id[i];
    if (lu == S_LU() && i >= 32 && i - 32 < g_ux.count) return g_ux.id[i - 32];
    return -1;
}

API void sq_LuSetID(Lineup *lu, int i, int v) {
    ensure_init();
    if ((u32)i < 32) { lu->id[i] = (u16)v; return; }
    if (lu == S_LU() && i >= 32 && i - 32 < EXT_CAP) {
        g_ux.id[i - 32] = (u16)v;
        if (i - 32 >= g_ux.count) g_ux.count = i - 32 + 1;
    }
}

API int sq_LuGetIndex(Lineup *lu, int id) {
    ensure_init();
    int idx;
    lu_ptr_id(lu, (u16)id, &idx);
    return idx;
}

API int sq_LuHasPlayer(Lineup *lu, int id) {
    ensure_init();
    int idx;
    return lu_ptr_id(lu, (u16)id, &idx) != 0;
}

API void sq_LuSwap(Lineup *lu, int i, int j, void *tm) {
    ensure_init();
    (void)tm;
    u16 *a = lu_ptr_idx(lu, i), *b = lu_ptr_idx(lu, j);
    if (!a || !b) return;
    u16 t = *a; *a = *b; *b = t;
    if (lu == S_LU() && ((i >= 32) != (j >= 32))) resync_partition();
}

API void sq_LuSwapByID(Lineup *lu, int id1, int id2, void *tm) {
    ensure_init();
    (void)tm;
    int ia, ib;
    u16 *a = lu_ptr_id(lu, (u16)id1, &ia), *b = lu_ptr_id(lu, (u16)id2, &ib);
    if (!a || !b) return;
    u16 t = *a; *a = *b; *b = t;
    if (lu == S_LU() && ((ia >= 32) != (ib >= 32))) resync_partition();
}

API void sq_LuRemovePlayerByID(Lineup *lu, int id) {
    ensure_init();
    if (lu == S_LU()) {
        int k = ux_find(id);
        if (k >= 0) { ux_remove(k); return; }
    }
    orig_LuRemovePlayerByID(lu, id);
    if (lu == S_LU()) lineup_fill();              /* slot 32 moves up into slot 31 */
}

API void sq_LuSerialize(Lineup *lu, u8 *ser) {
    ensure_init();
    orig_LuSerialize(lu, ser);
    s32 ver = *(s32 *)(ser + 0x18);
    int saving = ser[0x1c] != 0;
    int live = lu == S_LU();
    LuExt *x = live ? &g_ux : &s_ux_scratch;
    if (ver < SAVE_GATE) {
        if (!saving && live) ux_clear(&g_ux);
        return;
    }
    if (!live) ux_clear(&s_ux_scratch);
    u8 c = (u8)x->count;
    SerU8(ser, &c, SAVE_GATE);
    for (int i = 0; i < EXT_STORE; ++i) SerU16(ser, &x->id[i], SAVE_GATE);
    if (!saving) {
        x->count = c > EXT_CAP ? EXT_CAP : c;
        for (int i = x->count; i < EXT_STORE; ++i) x->id[i] = EMPTY_ID;
    }
}

API void sq_LuReset(Lineup *lu) {
    ensure_init();
    orig_LuReset(lu);
    if (lu == S_LU()) ux_clear(&g_ux);
}

API void *sq_LuCtor(Lineup *lu) {
    ensure_init();
    void *r = orig_LuCtor(lu);
    if (lu == S_LU()) ux_clear(&g_ux);
    return r;
}

/* the 32-part goes through the original body (created_caps.py re-targets its id range there); the
 * overflow uses CDataBase::IsCreatedPlayerID, which created_caps.py patches the same way */
API int sq_LuHaveCreatedPlayerInSquad(Lineup *lu) {
    ensure_init();
    if (orig_LuHaveCreatedPlayerInSquad(lu)) return 1;
    if (lu == S_LU())
        for (int k = 0; k < g_ux.count; ++k) if (IsCreatedPlayerID(g_ux.id[k])) return 1;
    return 0;
}

API void sq_ForceFirst11(Lineup *lu, int id) {
    ensure_init();
    if (lu == S_LU() && lu->n >= 32) {
        int k = ux_find(id);
        if (k >= 0) {
            u16 t = lu->id[31]; lu->id[31] = g_ux.id[k]; g_ux.id[k] = t;
            resync_partition();
        }
    }
    orig_ForceFirst11(lu, id);
}

/* total lineup count (call-site redirect of CTeamLineup::GetPlayerCount) */
API int sq_lineup_count(Lineup *lu) {
    ensure_init();
    int n = lu_main(lu);
    if (lu == S_LU()) n += g_ux.count;
    return n;
}

/* ================= team management ================= */
static State *state_find(u8 *tm, int id) {
    State *ms = tm_states(tm);
    for (int i = 0; i < 32; ++i) if ((u32)ms[i].id == (u32)id) return &ms[i];
    if (tm == S_TM()) return sx_find(id);
    return 0;
}

API State *sq_GetSeasonPlayerStateByID(u8 *tm, int id) {
    ensure_init();
    return state_find(tm, id);
}

API void sq_TmAddPlayerState(u8 *tm, int id) {
    ensure_init();
    if (state_find(tm, (u16)id)) return;
    State *ms = tm_states(tm), *f = 0;
    for (int i = 0; i < 32; ++i) if (ms[i].id == EMPTY_ID) { f = &ms[i]; break; }
    if (!f && tm == S_TM()) f = sx_free();
    if (f) state_setup(f, id);
}

API void sq_RemovePlayerState(u8 *tm, int id) {
    ensure_init();
    State *ms = tm_states(tm);
    for (int i = 0; i < 32; ++i) if (ms[i].id == (u32)id) { state_clear(&ms[i]); return; }
    if (tm == S_TM()) { State *s = sx_find(id); if (s) state_clear(s); }
}

API void sq_TmAddPlayer(u8 *tm, int id) {
    ensure_init();
    if (tm != S_TM()) { orig_TmAddPlayer(tm, id); return; }
    if (S_LU()->n < 32) {
        orig_TmAddPlayer(tm, id);
        resync_partition();
        return;
    }
    if (g_ux.count >= EXT_CAP || lu_slot(id) >= 0) return;
    g_ux.id[g_ux.count++] = (u16)id;               /* the owner CTeam keeps its 32-part count */
    sq_TmAddPlayerState(tm, id);
    resync_partition();
}

API void sq_TmRemovePlayerByID(u8 *tm, int id) {
    ensure_init();
    if (tm != S_TM()) { orig_TmRemovePlayerByID(tm, id); return; }
    orig_TmRemovePlayerByID(tm, id);
    u8 *owner = tm_owner(tm);
    if (owner) owner[0x148] = (u8)lu_main(S_LU());  /* 32-part count after a possible pull-up */
    State *s = sx_find(id);
    if (s) state_clear(s);
    resync_partition();
}

/* stock Verify removes lineup players missing from the link 32-part; keep link-overflow players */
API void sq_verify_remove(u8 *tm, int id) {
    ensure_init();
    if (tm == S_TM() && lx_find(id) >= 0) return;
    sq_TmRemovePlayerByID(tm, id);
}

API void sq_TmSerialize(u8 *tm, u8 *ser) {
    ensure_init();
    orig_TmSerialize(tm, ser);
    s32 ver = *(s32 *)(ser + 0x18);
    int saving = ser[0x1c] != 0;
    int live = tm == S_TM();
    State *x = live ? g_sx : s_sx_scratch;
    if (ver < SAVE_GATE) {
        if (!saving && live) for (int i = 0; i < EXT_STORE; ++i) state_clear(&g_sx[i]);
        return;
    }
    if (!live) for (int i = 0; i < EXT_STORE; ++i) state_clear(&s_sx_scratch[i]);
    for (int i = 0; i < EXT_STORE; ++i) StateSerialize(&x[i], ser);
}

API void sq_TmReset(u8 *tm) {
    ensure_init();
    orig_TmReset(tm);
    if (tm == S_TM()) for (int i = 0; i < EXT_STORE; ++i) state_clear(&g_sx[i]);
}

API void sq_TmNextSeason(u8 *tm) {
    ensure_init();
    orig_TmNextSeason(tm);
    if (tm != S_TM() || tm[0x190] != 1) return;
    for (int i = 0; i < EXT_STORE; ++i) {
        if (g_sx[i].id == EMPTY_ID) continue;
        g_sx[i].injury = 0; g_sx[i].energy = 0x927c; g_sx[i].susp = 0; g_sx[i].yellows = 0;
    }
}

API int sq_EnergyReplenish(u8 *tm, int full, int secs) {
    ensure_init();
    int r = orig_EnergyReplenish(tm, full, secs);
    if (tm != S_TM()) return r;
    float rate = 0.0f;
    if (!full) {
        int v = CConfigGetVar(0x1d);
        rate = (float)v;
        if (v <= 0) {
            int s = GetCreditRechargeSeconds(0);
            rate = (float)((double)s / 60.0);
            if (!(rate > 0.0f)) return r;          /* stock returns before touching any state */
        }
    }
    float inc = (18750.0f / rate) * (float)secs;
    int allfull = 1;
    for (int i = 0; i < EXT_STORE; ++i) {
        State *s = &g_sx[i];
        if (s->id == EMPTY_ID || s->injury || s->energy >= 0x927c) continue;
        if (full) { s->energy = 0x927c; continue; }
        int e = (int)(inc + (float)s->energy);
        if (e >= 0x927c) e = 0x927c;
        s->energy = (u16)e;
        allfull &= (e & 0xfffc) > 0x927b;
    }
    return r & allfull;
}

API void sq_ReduceInjSusp(u8 *tm) {
    ensure_init();
    orig_ReduceInjSusp(tm);
    if (tm != S_TM()) return;
    for (int i = 0; i < EXT_STORE; ++i) {
        State *s = &g_sx[i];
        if (s->id == EMPTY_ID) continue;
        if (s->injury) StateReduceInjury(s);
        if (s->susp) StateReduceSuspension(s);
    }
}

API int sq_IsEnergyFullForAllPlayers(u8 *tm) {
    ensure_init();
    State *ms = tm_states(tm);
    for (int i = 0; i < 32; ++i)
        if (ms[i].id != EMPTY_ID && !ms[i].injury && ms[i].energy < 0x927c) return 0;
    if (tm == S_TM())
        for (int i = 0; i < EXT_STORE; ++i)
            if (g_sx[i].id != EMPTY_ID && !g_sx[i].injury && g_sx[i].energy < 0x927c) return 0;
    return 1;
}

API int sq_GetNumInjuries(u8 *tm) {
    ensure_init();
    State *ms = tm_states(tm);
    int n = 0;
    for (int i = 0; i < 32; ++i) if (ms[i].id != EMPTY_ID && ms[i].injury) n++;
    if (tm == S_TM()) for (int i = 0; i < EXT_STORE; ++i) if (g_sx[i].id != EMPTY_ID && g_sx[i].injury) n++;
    return n;
}

API int sq_CanSwap(u8 *tm, int id1, int id2, int idx1, int idx2) {
    ensure_init();
    if (tm == S_TM()) {
        if (idx1 < 0) idx1 = sq_LuGetIndex(S_LU(), (u16)id1);
        if (idx2 < 0) idx2 = sq_LuGetIndex(S_LU(), (u16)id2);
        if (idx1 >= 32) idx1 = 31;                  /* overflow players are reserves */
        if (idx2 >= 32) idx2 = 31;
    }
    return orig_CanSwap(tm, id1, id2, idx1, idx2);
}

static int verify_blocked(void) {
    return *(s32 *)(MatchSetup_ms_tInfo + 0x10) == 8 || MC_bResettingProfile[0] || CCore_InGame();
}

/* Verify re-enters itself (Verify -> RemovePlayerByID -> tail Verify): resync once, when the outermost
 * Verify returns, so the stock loops never see the tables change under them. */
u32 g_verify_depth HIDDEN;
API void sq_TmVerify(u8 *tm) {
    ensure_init();
    g_verify_depth++;
    orig_TmVerify(tm);
    g_verify_depth--;
    if (!g_verify_depth && tm == S_TM() && !verify_blocked()) resync_full();
}

API void sq_TmSetDefaults(u8 *tm, int team, int type, void *custom, void *players) {
    ensure_init();
    orig_TmSetDefaults(tm, team, type, custom, players);
    if (tm != S_TM()) return;
    ux_clear(&g_ux);
    for (int i = 0; i < EXT_STORE; ++i) state_clear(&g_sx[i]);
    Link *L = live_user_link();
    if (team == USER_TEAM && L && S_LU()->n >= 32) {
        for (int k = 0; k < g_lx.count && g_ux.count < EXT_CAP; ++k) {
            g_ux.id[g_ux.count] = (u16)g_lx.id[k];
            if (type == 1) state_setup(&g_sx[g_ux.count], g_lx.id[k]);
            g_ux.count++;
        }
    }
    resync_partition();
}

/* ================= CTeam / front end ================= */
static u8 *pool_find(int id) {
    for (int i = 0; i < POOL_N; ++i) if (g_pool_id[i] != EMPTY_ID && g_pool_id[i] == (u16)id) return g_pool[i];
    return 0;
}
static u8 *pool_alloc(int id) {
    u8 *p = pool_find(id);
    if (p) return p;
    for (int i = 0; i < POOL_N; ++i) if (g_pool_id[i] == EMPTY_ID) { g_pool_id[i] = (u16)id; return g_pool[i]; }
    /* full: recycle round-robin, never an entry of a current overflow player */
    for (int t = 0; t < POOL_N; ++t) {
        u32 i = g_pool_next++ & (POOL_N - 1);
        if (ux_find(g_pool_id[i]) < 0) { g_pool_id[i] = (u16)id; return g_pool[i]; }
    }
    u32 i = g_pool_next++ & (POOL_N - 1);
    g_pool_id[i] = (u16)id;
    return g_pool[i];
}
static void pool_fill(u8 *info, int id, int team, int x) {
    memset(info, 0, INFO_SIZE);
    TPlayerInfoCtor(info);
    if (!GetPlayerInfo(info, id, team, 1, 0, x, 0, 0)) *(u16 *)info = (u16)id;
    /* CDataBase::SetPlayerGameVarsFromSeasonState */
    State *st = state_find(S_TM(), id);
    info[0xac] = 0;
    *(u32 *)(info + 0xa8) = 0;
    *(u16 *)(info + 0xa6) = 0x927c;
    if (st) { *(u16 *)(info + 0xa6) = st->energy; info[0xab] = st->susp; }
}

API void sq_PlayersLoad(void *db, u8 *ct, u8 *tm, int x) {
    ensure_init();
    orig_PlayersLoad(db, ct, tm, x);
    if (tm != S_TM()) return;
    for (int i = 0; i < POOL_N; ++i) g_pool_id[i] = EMPTY_ID;
    for (int k = 0; k < g_ux.count; ++k) {
        u8 *p = pool_alloc(g_ux.id[k]);
        pool_fill(p, g_ux.id[k], *(s32 *)ct, x);
    }
}

API u8 *sq_CTeamGetPlayerInfoByID(u8 *ct, int id) {
    ensure_init();
    u8 *r = orig_CTeamGetPlayerInfoByID(ct, id);
    if (r || ct_tm(ct) != S_TM()) return r;
    r = pool_find(id);
    if (!r && lu_slot(id) >= 0) { r = pool_alloc(id); pool_fill(r, id, *(s32 *)ct, -1); }
    return r;
}

API void sq_CTeamSwapPlayers(u8 *ct, int i, int j) {
    ensure_init();
    if ((u32)i < 32 && (u32)j < 32) { orig_CTeamSwapPlayers(ct, i, j); return; }
    if (ct_tm(ct) != S_TM() || i < 0 || j < 0) return;
    if (i >= 32 && j >= 32) { UpdateTeamRoles(ct); return; }  /* pool is keyed by player id */
    int k = i < 32 ? i : j;
    u8 *pk = *(u8 **)(ct + 0x100c) + k * INFO_SIZE;
    int newid = sq_LuGetID(S_LU(), k);
    u8 *src = pool_find(newid);
    if (!src) { src = pool_alloc(newid); pool_fill(src, newid, *(s32 *)ct, -1); }
    u8 old[INFO_SIZE];
    memcpy(old, pk, INFO_SIZE);
    memcpy(pk, src, INFO_SIZE - 1);                /* byte 0xaf stays with the slot, like the stock swap */
    u8 *dst = pool_alloc(*(u16 *)old);
    memcpy(dst, old, INFO_SIZE);
    UpdateTeamRoles(ct);
}

/* squad screen count: 32-part of the CTeam + season overflow */
API int sq_team_count(u8 *ct) {
    ensure_init();
    int n = ct[0x148];
    if (ct_tm(ct) == S_TM()) n += g_ux.count;
    return n;
}
